version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build
          command: echo "Build step"

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Test
          command: echo "Test step"

workflows:
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build
          filters:
            branches:
              only: main
